apiVersion: v1
kind: Pod
metadata:
  name: pod-migration
  namespace: prueba
spec:
  containers:
  - name: migration
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: nuevo
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nuevo
    persistentVolumeClaim:
      claimName: demo-pvc-rwx