apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tarifario
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/shovelmans/jorgewiki.git
    targetRevision: main
    path: si-tarifario-sandetel-k8s/charts/tarifario

  destination:
    server: https://kubernetes.default.svc
    namespace: tarifario

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true