mariadb:
  name: mariadb
  replicas: 1
  image: mariadb:10.3
  port: 3306

  serviceName: mariadb
  secretName: mariadb
  pvcName: mariadb
  volumeName: mariadb-data
  configMapName: mariadb-initdb

  database:
    name: tarifario
    user: tarifario
    password: password
    rootPassword: root_password

  persistence:
    accessMode: ReadWriteOnce
    size: 1Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi