apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mariadb.livenessConfigMapName }}
  labels:
    app: {{ .Values.mariadb.name }}
data:
  liveness.sh: |
{{ .Files.Get "files/liveness.sh" | indent 4 }}
