apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mariadb.secretName }}
  labels:
    app: {{ .Values.mariadb.name }}
type: Opaque
stringData:
  database-name: {{ .Values.mariadb.database.name | quote }}
  database-user: {{ .Values.mariadb.database.user | quote }}
  database-password: {{ .Values.mariadb.database.password | quote }}
  database-root-password: {{ .Values.mariadb.database.rootPassword | quote }}