apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mariadb.serviceName }}
  labels:
    app: {{ .Values.mariadb.name }}
spec:
  selector:
    app: {{ .Values.mariadb.name }}
  ports:
    - name: mysql
      port: {{ .Values.mariadb.port }}
      targetPort: {{ .Values.mariadb.port }}
      protocol: TCP
  type: ClusterIP