apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mariadb.name }}
  labels:
    app: {{ .Values.mariadb.name }}
spec:
  replicas: {{ .Values.mariadb.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.mariadb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mariadb.name }}
    spec:
      containers:
        - name: {{ .Values.mariadb.name }}
          image: {{ .Values.mariadb.image | quote }}
          ports:
            - containerPort: {{ .Values.mariadb.port }}
              protocol: TCP
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mariadb.secretName }}
                  key: database-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mariadb.secretName }}
                  key: database-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mariadb.secretName }}
                  key: database-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mariadb.secretName }}
                  key: database-name
          volumeMounts:
            - name: {{ .Values.mariadb.volumeName }}
              mountPath: /var/lib/mysql
            - name: mariadb-initdb
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
            - name: mariadb-readiness
              mountPath: /opt/checks/readiness.sh
              subPath: readiness.sh
            - name: mariadb-liveness
              mountPath: /opt/checks/liveness.sh
              subPath: liveness.sh
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - /opt/checks/readiness.sh
            initialDelaySeconds: {{ .Values.mariadb.probes.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.mariadb.probes.readiness.timeoutSeconds }}
            periodSeconds: {{ .Values.mariadb.probes.readiness.periodSeconds }}
            successThreshold: {{ .Values.mariadb.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.mariadb.probes.readiness.failureThreshold }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - /opt/checks/liveness.sh
            initialDelaySeconds: {{ .Values.mariadb.probes.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.mariadb.probes.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.mariadb.probes.liveness.periodSeconds }}
            successThreshold: {{ .Values.mariadb.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.mariadb.probes.liveness.failureThreshold }}
          resources:
            requests:
              cpu: {{ .Values.mariadb.resources.requests.cpu }}
              memory: {{ .Values.mariadb.resources.requests.memory }}
            limits:
              cpu: {{ .Values.mariadb.resources.limits.cpu }}
              memory: {{ .Values.mariadb.resources.limits.memory }}
      volumes:
        - name: {{ .Values.mariadb.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.mariadb.pvcName }}
        - name: mariadb-initdb
          configMap:
            name: {{ .Values.mariadb.configMapName }}
        - name: mariadb-readiness
          configMap:
            name: {{ .Values.mariadb.readinessConfigMapName }}
        - name: mariadb-liveness
          configMap:
            name: {{ .Values.mariadb.livenessConfigMapName }}
