apiVersion: v1
kind: Service
metadata:
  name: tarifario-backend-v2
  namespace: tarifario
spec:
  selector:
    app: tarifario-backend-v2
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP