apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mariadb.pvcName }}
  labels:
    app: {{ .Values.mariadb.name }}
spec:
  accessModes:
    - {{ .Values.mariadb.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.size }}